services:
  budgetmanagerdb:
    image: budget-manager-postgres-database:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    
  budgetmanagerapi:
    image: budgetmanagerapi
    build:
      context: .
      dockerfile: BudgetManagerApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: "http://+:8080;https://+:8081"
      Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      DB_CONNECTION_STRING: "ezXrSMUPTxM+l3nk1OMDGovzbjVOCyN1Zf7fvxXcHJwcILGtjK6seOpfbjAga+g7/Ki0/aSw2ryyZKCCo54yoe0LbBKQUP51z37kBrWa6IElu+bpjlLBu2wgO0HAsmt4"
      DB_PROVIDER: "NPGSQL"
      BM_DEFAULT_ENCRYPTION_KEY: "KHigh9XVFITSywTHSReS3g=="
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on: 
     - budgetmanagerdb
    volumes:
      - ${HOME}/.aspnet/https:/https:ro